[package]
name = "bevy_enhanced_input_macros"
version = "0.1.0"
description = "Bevy Enhanced Input Macros"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
